---
- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart clawdbot gateway
  ansible.builtin.systemd:
    name: clawdbot
    state: restarted
  when: ansible_os_family == 'Debian'
